#! /bin/bash

echo Unpacking Hadoop
tar zxf hadoop-2.7.3.tar.gz
ln -s hadoop-2.7.3 hadoop

export HADOOP_HOME=$PWD/hadoop
PATH=$PATH:$HADOOP_HOME/bin

# Fix script bugs
echo Configuring Hadoop
echo export JAVA_HOME=$JAVA_HOME >> hadoop/etc/hadoop/hadoop-env.sh

cat > hadoop/etc/hadoop/core-site.xml << EOF
<configuration>
    <property>
        <name>fs.defaultFS</name>
        <value>hdfs://localhost:9000</value>
    </property>
</configuration>
EOF

cat > hadoop/etc/hadoop/hdfs-site.xml << EOF
<configuration>
    <property>
        <name>dfs.replication</name>
        <value>1</value>
    </property>
</configuration>
EOF

cat > hadoop/etc/hadoop/mapred-site.xml << EOF
<configuration>
    <property>
        <name>mapreduce.framework.name</name>
        <value>yarn</value>
    </property>
</configuration>
EOF

cat > hadoop/etc/hadoop/yarn-site.xml << EOF
<configuration>
    <property>
        <name>yarn.nodemanager.aux-services</name>
        <value>mapreduce_shuffle</value>
    </property>
    <property>
        <name>yarn.nodemanager.aux-services.mapreduce_shuffle.class</name>
        <value>org.apache.hadoop.mapred.ShuffleHandler</value>
    </property>
</configuration>
EOF

echo Hadoop installed
