#! /bin/bash
#
# File: cleanup
#
# Purpose: cleans up all artifacts creating by running the lab exercise.
#


docker rm -f mysql

docker rm -f $(docker ps -aq)
docker rmi -f $(docker images -q)

docker volume rm $(docker volume ls -q)
